motion_controller_slx:
  ros__parameters:
    spdMax: 4.5
    angleMax: 0.515
    ackermann: 1.0
    effortMax: 0.6
    steer_rate_dps: 0.0
    acc_rate_mps: 0.0
    drive_by_2: False
    FWS: True
    driveMode: 1.0 #0 front, 1 rear, 2 both
    isTcsEnabled: False
    tcsK1Sgne: 0.8
    tcsK2e: 10.0
    tcsFxEstimatedMu: 0.66
    tcsKappaDesired: 0.3
